#include "cuda/CudaBackend.hpp"
#ifdef SOVEREIGN_HAS_CUDA
#include <cuda_runtime.h>
#include <cublas_v2.h>
#include <cusparse.h>
#include <algorithm>

namespace sovereign::cuda {
DeviceInfo deviceInfo(int device) {
  DeviceInfo out; int count=0;
  if (cudaGetDeviceCount(&count)!=cudaSuccess || count==0) return out;
  out.available=true; out.count=count; out.selected=std::clamp(device,0,count-1);
  cudaDeviceProp p{}; check(cudaGetDeviceProperties(&p,out.selected),"cudaGetDeviceProperties");
  out.name=p.name; out.major=p.major; out.minor=p.minor; out.globalMemory=p.totalGlobalMem;
  out.runtime=std::to_string(CUDART_VERSION/1000)+"."+std::to_string((CUDART_VERSION%1000)/10); return out;
}
std::string deviceInfoText(int device) { auto d=deviceInfo(device); if(!d.available) return "CUDA Available: NO\nGPU Count: 0\n"; return "CUDA Available: YES\nGPU Count: "+std::to_string(d.count)+"\nDevice: "+d.name+"\nCompute Capability: "+std::to_string(d.major)+"."+std::to_string(d.minor)+"\nGlobal Memory: "+std::to_string(d.globalMemory)+" bytes\nCUDA Runtime: "+d.runtime+"\n"; }
Context::Context(int device) { auto d=deviceInfo(device); if(!d.available) return; check(cudaSetDevice(d.selected),"cudaSetDevice"); cudaStream_t s; check(cudaStreamCreate(&s),"cudaStreamCreate"); cublasHandle_t b; check(cublasCreate(&b),"cublasCreate"); cusparseHandle_t sp; check(cusparseCreate(&sp),"cusparseCreate"); check(cublasSetStream(b,s),"cublasSetStream"); check(cusparseSetStream(sp,s),"cusparseSetStream"); stream_=s; blas_=b; sparse_=sp; available_=true; }
Context::~Context() { if(!available_) return; cusparseDestroy((cusparseHandle_t)sparse_); cublasDestroy((cublasHandle_t)blas_); cudaStreamDestroy((cudaStream_t)stream_); }
void Context::synchronize() const { check(cudaStreamSynchronize((cudaStream_t)stream_),"cudaStreamSynchronize"); }
void Context::axpy(double a,const double*x,double*y,std::size_t n) const { double *dx,*dy; check(cudaMalloc(&dx,n*sizeof(double)),"cudaMalloc"); check(cudaMalloc(&dy,n*sizeof(double)),"cudaMalloc"); check(cudaMemcpyAsync(dx,x,n*sizeof(double),cudaMemcpyHostToDevice,(cudaStream_t)stream_),"H2D"); check(cudaMemcpyAsync(dy,y,n*sizeof(double),cudaMemcpyHostToDevice,(cudaStream_t)stream_),"H2D"); check(cublasDaxpy((cublasHandle_t)blas_,(int)n,&a,dx,1,dy,1),"cublasDaxpy"); check(cudaMemcpyAsync(y,dy,n*sizeof(double),cudaMemcpyDeviceToHost,(cudaStream_t)stream_),"D2H"); synchronize(); cudaFree(dx); cudaFree(dy); }
double Context::dot(const double*x,const double*y,std::size_t n) const { double *dx,*dy,out=0; check(cudaMalloc(&dx,n*sizeof(double)),"cudaMalloc"); check(cudaMalloc(&dy,n*sizeof(double)),"cudaMalloc"); check(cudaMemcpy(dx,x,n*sizeof(double),cudaMemcpyHostToDevice),"H2D"); check(cudaMemcpy(dy,y,n*sizeof(double),cudaMemcpyHostToDevice),"H2D"); check(cublasDdot((cublasHandle_t)blas_,(int)n,dx,1,dy,1,&out),"cublasDdot"); synchronize(); cudaFree(dx); cudaFree(dy); return out; }
void Context::gemv(const double*A,std::size_t r,std::size_t c,const double*x,double*y) const { double *dA,*dx,*dy; check(cudaMalloc(&dA,r*c*sizeof(double)),"cudaMalloc");check(cudaMalloc(&dx,c*sizeof(double)),"cudaMalloc");check(cudaMalloc(&dy,r*sizeof(double)),"cudaMalloc");check(cudaMemcpy(dA,A,r*c*sizeof(double),cudaMemcpyHostToDevice),"H2D");check(cudaMemcpy(dx,x,c*sizeof(double),cudaMemcpyHostToDevice),"H2D");check(cudaMemcpy(dy,y,r*sizeof(double),cudaMemcpyHostToDevice),"H2D");double one=1,zero=0;check(cublasDgemv((cublasHandle_t)blas_,CUBLAS_OP_N,(int)r,(int)c,&one,dA,(int)r,dx,1,&zero,dy,1),"cublasDgemv");check(cudaMemcpy(y,dy,r*sizeof(double),cudaMemcpyDeviceToHost),"D2H");synchronize();cudaFree(dA);cudaFree(dx);cudaFree(dy);}
void Context::spmv(const nla::CSRMatrix&A,const double*x,double*y,double alpha,double beta) const { int*r=nullptr,*ci=nullptr;double*av=nullptr,*dx=nullptr,*dy=nullptr;std::vector<int> rp(A.rowPointers().size()),cp(A.columnIndices().size());for(size_t i=0;i<rp.size();++i)rp[i]=(int)A.rowPointers()[i];for(size_t i=0;i<cp.size();++i)cp[i]=(int)A.columnIndices()[i];check(cudaMalloc(&r,rp.size()*sizeof(int)),"cudaMalloc");check(cudaMalloc(&ci,cp.size()*sizeof(int)),"cudaMalloc");check(cudaMalloc(&av,A.nonZeros()*sizeof(double)),"cudaMalloc");check(cudaMalloc(&dx,A.cols()*sizeof(double)),"cudaMalloc");check(cudaMalloc(&dy,A.rows()*sizeof(double)),"cudaMalloc");check(cudaMemcpy(r,rp.data(),rp.size()*sizeof(int),cudaMemcpyHostToDevice),"H2D");check(cudaMemcpy(ci,cp.data(),cp.size()*sizeof(int),cudaMemcpyHostToDevice),"H2D");check(cudaMemcpy(av,A.values().data(),A.nonZeros()*sizeof(double),cudaMemcpyHostToDevice),"H2D");check(cudaMemcpy(dx,x,A.cols()*sizeof(double),cudaMemcpyHostToDevice),"H2D");check(cudaMemcpy(dy,y,A.rows()*sizeof(double),cudaMemcpyHostToDevice),"H2D");cusparseSpMatDescr_t m;cusparseDnVecDescr_t xv,yv;check(cusparseCreateCsr(&m,A.rows(),A.cols(),A.nonZeros(),r,ci,av,CUSPARSE_INDEX_32I,CUSPARSE_INDEX_32I,CUSPARSE_INDEX_BASE_ZERO,CUDA_R_64F),"cusparseCreateCsr");check(cusparseCreateDnVec(&xv,A.cols(),dx,CUDA_R_64F),"cusparseCreateDnVec");check(cusparseCreateDnVec(&yv,A.rows(),dy,CUDA_R_64F),"cusparseCreateDnVec");size_t bytes=0;check(cusparseSpMV_bufferSize((cusparseHandle_t)sparse_,CUSPARSE_OPERATION_NON_TRANSPOSE,&alpha,m,xv,&beta,yv,CUDA_R_64F,CUSPARSE_SPMV_ALG_DEFAULT,&bytes),"cusparseSpMV_bufferSize");void*buf=nullptr;check(cudaMalloc(&buf,bytes),"cudaMalloc");check(cusparseSpMV((cusparseHandle_t)sparse_,CUSPARSE_OPERATION_NON_TRANSPOSE,&alpha,m,xv,&beta,yv,CUDA_R_64F,CUSPARSE_SPMV_ALG_DEFAULT,buf),"cusparseSpMV");check(cudaMemcpy(y,dy,A.rows()*sizeof(double),cudaMemcpyDeviceToHost),"D2H");synchronize();cusparseDestroySpMat(m);cusparseDestroyDnVec(xv);cusparseDestroyDnVec(yv);cudaFree(buf);cudaFree(r);cudaFree(ci);cudaFree(av);cudaFree(dx);cudaFree(dy);}
}
#else
namespace sovereign::cuda { DeviceInfo deviceInfo(int){return {}; } std::string deviceInfoText(int){return "CUDA Available: NO\nGPU Count: 0\n";} Context::Context(int){} Context::~Context()=default; void Context::synchronize()const{} void Context::axpy(double,const double*,double*,std::size_t)const{throw std::runtime_error("CUDA backend not compiled");} double Context::dot(const double*,const double*,std::size_t)const{throw std::runtime_error("CUDA backend not compiled");} void Context::gemv(const double*,std::size_t,std::size_t,const double*,double*)const{throw std::runtime_error("CUDA backend not compiled");} void Context::spmv(const nla::CSRMatrix&,const double*,double*,double,double)const{throw std::runtime_error("CUDA backend not compiled");} }
#endif
