#include "presolve/Presolver.hpp"
#include "model/Input.hpp"
#include "core/SparseMatrix.hpp"
#include "model/Classification.hpp"
#include "lp/Verifier.hpp"
#include "presolve/Postsolve.hpp"
#include <cassert>
#include <fstream>
#include <iostream>
using namespace sovereign;
int main(){
    { const char* path="sovereign_mps_ranges_test.mps";std::ofstream f(path);f<<"NAME RANGE\nOBJSENSE\n MAX\nROWS\n N OBJ\n L CAP\nCOLUMNS\n X OBJ 1 CAP 1\nRHS\n R CAP 4\n ALT CAP 99\nRANGES\n R CAP 2\n ALT CAP 50\nBOUNDS\n BV BND X\n UP OTHER X 0.5\nENDATA\n";f.close();Model parsed=parseMPS(path);std::remove(path);assert(parsed.sense==Sense::Maximize);assert(parsed.variables.size()==1&&parsed.variables[0].type==VariableType::Binary&&parsed.variables[0].upper==1);assert(parsed.constraints.size()==2);assert(parsed.constraints[0].relation==Relation::GreaterEqual&&parsed.constraints[0].rhs==4);assert(parsed.constraints[1].relation==Relation::LessEqual&&parsed.constraints[1].rhs==6); }
    SparseMatrix matrix(2,2); matrix.set(0,0,2); matrix.set(0,1,3); assert(matrix.get(0,1)==3); assert(matrix.multiply({1,2})[0]==8); assert(matrix.column(0).size()==1);
    Model fixed; fixed.variables.push_back({0,0,"x",VariableType::Continuous,2,2,true}); fixed.objective[0]=3; auto a=Presolver{}.run(fixed); assert(a.stats.fixedVariables==1); assert(a.passStats.size()==2); assert(a.passStats[0].variablesBefore==1&&a.passStats[0].variablesAfter==0); assert(a.passStats[0].fixedVariables==1); assert(a.passStats[0].percentageReduction>0.0);
    Model infeasible; infeasible.variables.push_back({0,0,"x",VariableType::Continuous,5,1,true}); assert(Presolver{}.run(infeasible).status==PresolveStatus::Infeasible);
    Model unbounded; unbounded.sense=Sense::Maximize; unbounded.variables.push_back({0,0,"x",VariableType::Continuous,0,INF,true}); unbounded.objective[0]=1; assert(Presolver{}.run(unbounded).status==PresolveStatus::Unbounded);
    Model lp; lp.variables.push_back({0,0,"x",VariableType::Continuous,0,10,true}); Constraint row;row.name="limit";row.coefficients[0]=1;row.relation=Relation::LessEqual;row.rhs=5;lp.constraints.push_back(row);auto b=Presolver{}.run(lp);assert(b.stats.boundTightenings==1);
    Model e; e.name="e2e"; e.variables.push_back({0,0,"x",VariableType::Continuous,0,INF,true}); e.variables.push_back({1,1,"y",VariableType::Continuous,0,INF,true}); e.variables.push_back({2,2,"z",VariableType::Continuous,0,INF,true}); e.objective[0]=2; e.objective[1]=1; Constraint eq;eq.originalId=0;eq.name="sum";eq.coefficients[0]=1;eq.coefficients[1]=1;eq.relation=Relation::Equal;eq.rhs=10;e.constraints.push_back(eq); Constraint fixz;fixz.originalId=1;fixz.name="fixz";fixz.coefficients[2]=1;fixz.relation=Relation::Equal;fixz.rhs=3;e.constraints.push_back(fixz); Constraint redundant;redundant.originalId=2;redundant.name="redundant";redundant.relation=Relation::LessEqual;redundant.rhs=0;e.constraints.push_back(redundant); auto pr=Presolver{}.run(e); assert(pr.stats.substitutions==1&&pr.stats.fixedVariables==1&&pr.stats.redundantRows>=1&&pr.stats.boundTightenings>=1); assert(pr.model.originalToActive.count(1)); assert(!pr.passStats.empty()); assert(pr.passStats.back().variablesAfter==activeVariableCount(pr.model)); assert(pr.passStats.back().constraintsAfter==activeConstraintCount(pr.model)); assert(pr.passStats.back().nonzerosAfter==activeNonzeroCount(pr.model)); Solution rs;rs.primal={4}; auto os=postsolve(e,pr,rs); assert(std::abs(os.primal[0]-6)<1e-9&&std::abs(os.primal[1]-4)<1e-9&&std::abs(os.primal[2]-3)<1e-9); assert(verify(e,os).feasible); Solution full;full.primal={0,4,0};auto fullPostsolve=postsolve(e,pr,full);assert(std::abs(fullPostsolve.primal[0]-6)<1e-9&&std::abs(fullPostsolve.primal[1]-4)<1e-9&&std::abs(fullPostsolve.primal[2]-3)<1e-9);assert(verify(e,fullPostsolve).feasible); assert(std::abs(os.objectiveValue-16)<1e-9);
    Model sparseFixed; sparseFixed.variables.push_back({0,0,"a",VariableType::Continuous,1,1,true}); sparseFixed.variables.push_back({1,1,"b",VariableType::Continuous,0,INF,true}); sparseFixed.variables.push_back({2,2,"c",VariableType::Continuous,1,1,true}); Constraint linked; linked.originalId=0; linked.coefficients[0]=1; linked.coefficients[1]=1; linked.coefficients[2]=-1; linked.relation=Relation::LessEqual; linked.rhs=2; sparseFixed.constraints.push_back(linked); auto indexedFixed=Presolver{}.run(sparseFixed); assert(indexedFixed.stats.fixedVariables==2); assert(indexedFixed.model.constraints.empty()); assert(std::abs(indexedFixed.model.variables[1].upper-2)<1e-9);
    Model diminishing; for(std::size_t i=0;i<20003;++i)diminishing.variables.push_back({i,i,"v",VariableType::Continuous,0,INF,true}); diminishing.variables[0].lower=2; diminishing.variables[0].upper=2; for(std::size_t i=0;i<10000;++i){Constraint row;row.originalId=i;row.coefficients[0]=1;row.coefficients[i+1]=1;row.coefficients[i+10001]=1;row.relation=Relation::LessEqual;row.rhs=100;diminishing.constraints.push_back(row);} Constraint second; second.coefficients[0]=1; second.coefficients[20001]=1; second.coefficients[20002]=1; second.relation=Relation::Equal; second.rhs=3; diminishing.constraints.push_back(second); auto adaptive=Presolver({},10,0,true).run(diminishing); if(adaptive.stats.fixedVariables!=1||adaptive.passStats.size()!=2||adaptive.terminationReason!="diminishing_returns"){std::cerr<<"adaptive presolve regression: fixed="<<adaptive.stats.fixedVariables<<" passes="<<adaptive.passStats.size()<<" termination="<<adaptive.terminationReason<<"\n";for(const auto& pass:adaptive.passStats)std::cerr<<"pass="<<pass.pass<<" work="<<pass.variablesBefore+pass.constraintsBefore+pass.nonzerosBefore<<" reduction="<<pass.percentageReduction<<" time="<<pass.timeMs<<" changed="<<pass.boundTightenings+pass.fixedVariables+pass.substitutions+pass.singletonReductions+pass.redundantRowsRemoved<<"\n";return 20;}
    Model budgetModel; for(std::size_t i=0;i<8192;++i)budgetModel.variables.push_back({i,i,"b"+std::to_string(i),VariableType::Continuous,0,INF,true}); Constraint budgetEq; budgetEq.coefficients[0]=1; budgetEq.coefficients[1]=1; budgetEq.relation=Relation::Equal; budgetEq.rhs=1; budgetModel.constraints.push_back(budgetEq); auto budgeted=Presolver({},10,1e-12,true).run(budgetModel); assert(budgeted.passStats.size()==1); assert(budgeted.terminationReason=="time_budget");
    Model integerBound;integerBound.variables.push_back({0,0,"i",VariableType::Integer,0,10,true});Constraint integerCap;integerCap.coefficients[0]=1;integerCap.relation=Relation::LessEqual;integerCap.rhs=1.5;integerBound.constraints.push_back(integerCap);auto integerReduced=Presolver{}.run(integerBound,true);assert(integerReduced.model.variables[0].upper==1.0);
    Model fractionalIntegerEquality;fractionalIntegerEquality.variables.push_back({0,0,"i",VariableType::Integer,0,10,true});Constraint fractionalFix;fractionalFix.coefficients[0]=1;fractionalFix.relation=Relation::Equal;fractionalFix.rhs=1.5;fractionalIntegerEquality.constraints.push_back(fractionalFix);assert(Presolver{}.run(fractionalIntegerEquality,true).status==PresolveStatus::Infeasible);
    Model integerSubstitution;integerSubstitution.variables.push_back({0,0,"i",VariableType::Integer,0,INF,true});integerSubstitution.variables.push_back({1,1,"y",VariableType::Continuous,0,INF,true});Constraint integerLink;integerLink.coefficients[0]=1;integerLink.coefficients[1]=1;integerLink.relation=Relation::Equal;integerLink.rhs=5;integerSubstitution.constraints.push_back(integerLink);auto integerSafe=Presolver{}.run(integerSubstitution,true);assert(integerSafe.stats.substitutions==0&&integerSafe.model.variables[0].active);
    return 0;
}
