#pragma once
#include "milp/LPRelaxation.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
#include <vector>
namespace sovereign {
enum class MILPStatus { Optimal, Infeasible, Unbounded, IterationLimit, NumericalFailure };
struct BranchNode { std::size_t nodeId=0,parentId=0,depth=0;Model model;double bound=0;LPRelaxationResult relaxation; };
struct MILPResult { MILPStatus status{MILPStatus::NumericalFailure};std::vector<double> solution;double objective=0,primalBound=0,dualBound=0,absoluteGap=0,relativeGap=0;std::size_t nodesCreated=0,nodesProcessed=0,nodesPruned=0,lpSolves=0,totalLPIterations=0,maxDepth=0;bool incumbentFound=false,verified=false;std::string message; };
class BranchAndBound { public: explicit BranchAndBound(double tol=1e-8,std::size_t limit=10000):tol_(tol),limit_(limit){}
 MILPResult solve(const Model& original,LPMethod method=LPMethod::RevisedSimplex) const {MILPResult out;bool min=original.sense==Sense::Minimize;std::vector<BranchNode> open;BranchNode root;root.nodeId=0;root.model=original;open.push_back(root);out.nodesCreated=1;double incumbent=min?std::numeric_limits<double>::infinity():-std::numeric_limits<double>::infinity();
  while(!open.empty()&&out.nodesProcessed<limit_){size_t pick=0;for(size_t i=1;i<open.size();++i)if((min?open[i].bound<open[pick].bound:open[i].bound>open[pick].bound))pick=i;BranchNode node=std::move(open[pick]);open.erase(open.begin()+pick);auto lr=solveLPRelaxation(node.model,method);++out.nodesProcessed;++out.lpSolves;out.totalLPIterations+=lr.iterations;node.relaxation=lr;node.bound=lr.bound;out.maxDepth=std::max(out.maxDepth,node.depth);if(lr.status==LPStatus::Infeasible){++out.nodesPruned;continue;}if(lr.status==LPStatus::Unbounded){out.status=MILPStatus::Unbounded;out.message="LP relaxation is unbounded";return out;}if(lr.status!=LPStatus::Optimal){out.status=MILPStatus::NumericalFailure;out.message="LP relaxation failed";return out;}if(out.incumbentFound&&((min&&lr.bound>=incumbent-tol_)||(!min&&lr.bound<=incumbent+tol_))){++out.nodesPruned;continue;}size_t branch=original.variables.size();for(const auto&v:original.variables)if((v.type==VariableType::Integer||v.type==VariableType::Binary)&&v.originalId<lr.solution.size()&&std::abs(lr.solution[v.originalId]-std::round(lr.solution[v.originalId]))>tol_){branch=v.originalId;break;}if(branch==original.variables.size()){if(!out.incumbentFound||(min?lr.objectiveValue<incumbent-tol_:lr.objectiveValue>incumbent+tol_)){incumbent=lr.objectiveValue;out.solution=lr.solution;out.objective=incumbent;out.incumbentFound=true;}++out.nodesPruned;continue;}
    double value=lr.solution[branch],lo=std::floor(value),hi=std::ceil(value);Model left=node.model,right=node.model;left.variables[branch].upper=std::min(left.variables[branch].upper,lo);right.variables[branch].lower=std::max(right.variables[branch].lower,hi);if(left.variables[branch].lower<=left.variables[branch].upper+tol_){BranchNode c;c.nodeId=out.nodesCreated++;c.parentId=node.nodeId;c.depth=node.depth+1;c.model=std::move(left);open.push_back(std::move(c));}else ++out.nodesPruned;if(right.variables[branch].lower<=right.variables[branch].upper+tol_){BranchNode c;c.nodeId=out.nodesCreated++;c.parentId=node.nodeId;c.depth=node.depth+1;c.model=std::move(right);open.push_back(std::move(c));}else ++out.nodesPruned;}
  if(!out.incumbentFound){out.status=MILPStatus::Infeasible;out.message="no integer-feasible solution";return out;}out.status=open.empty()?MILPStatus::Optimal:MILPStatus::IterationLimit;out.primalBound=incumbent;out.dualBound=incumbent;if(!open.empty()){out.dualBound=open.front().bound;for(auto&n:open)out.dualBound=min?std::min(out.dualBound,n.bound):std::max(out.dualBound,n.bound);}out.absoluteGap=std::abs(out.primalBound-out.dualBound);out.relativeGap=out.absoluteGap/std::max(1.0,std::abs(out.primalBound));out.verified=verify(original,out.solution,tol_);return out;}
 private: double tol_;std::size_t limit_;static bool verify(const Model&m,const std::vector<double>&x,double t){for(const auto&v:m.variables){if(v.originalId>=x.size()||x[v.originalId]<v.lower-t||(std::isfinite(v.upper)&&x[v.originalId]>v.upper+t))return false;if((v.type==VariableType::Integer||v.type==VariableType::Binary)&&std::abs(x[v.originalId]-std::round(x[v.originalId]))>t)return false;}for(const auto&c:m.constraints){double a=0;for(auto q:c.coefficients)a+=q.second*x[q.first];if(c.relation==Relation::Equal&&std::abs(a-c.rhs)>t)return false;if(c.relation==Relation::LessEqual&&a>c.rhs+t)return false;if(c.relation==Relation::GreaterEqual&&a<c.rhs-t)return false;}return true;}};
}
