#pragma once
#include "milp/LPRelaxation.hpp"
#include <cmath>
#include <string>
namespace sovereign {
enum class CuttingStatus { OptimalInteger, Infeasible, LPSolveFailed, CutLimitReached, IterationLimitReached, NumericalFailure };
struct CuttingPlaneResult { CuttingStatus status{CuttingStatus::NumericalFailure};std::vector<double> solution;double objective=0;std::size_t iterations=0,cutsGenerated=0,cutsAccepted=0,cutsRejected=0,lpSolves=0,fractionalVariables=0;bool verified=false;std::string method="Gomory cutting plane"; };
class GomoryCutGenerator { public: explicit GomoryCutGenerator(double t=1e-8):tol_(t){} bool generate(const LPResult& lp,const Model& model,Constraint& cut,std::size_t& source) const {for(const auto& row:lp.gomoryRows){double norm=0,lhs=0;for(std::size_t i=0;i<row.coefficients.size();++i){double a=row.coefficients[i];if(!std::isfinite(a))return false;if(std::abs(a)>tol_){cut.coefficients[i]=a;norm+=std::abs(a);lhs+=a*lp.solution.primal[i];}}if(norm<=tol_)continue;cut.name="gomory_"+std::to_string(row.sourceVariable)+"_"+std::to_string(model.constraints.size());cut.relation=Relation::GreaterEqual;cut.rhs=row.rhs;source=row.sourceVariable;if(cut.rhs-lhs>tol_)return true;cut.coefficients.clear();}return false;} private: double tol_;};
class CuttingPlaneSolver {public: CuttingPlaneSolver(double tol=1e-8,std::size_t cuts=100,std::size_t iters=100):tol_(tol),maxCuts_(cuts),maxIterations_(iters){} CuttingPlaneResult solve(const Model& original) const {CuttingPlaneResult out;Model work=relaxMILP(original);GomoryCutGenerator gen(tol_);for(std::size_t it=0;it<maxIterations_;++it){LPResult lp=LPSolver{}.solve(work,LPMethod::RevisedSimplex,10000,&original);++out.lpSolves;out.iterations=it+1;if(lp.status==LPStatus::Infeasible){out.status=CuttingStatus::Infeasible;return out;}if(lp.status!=LPStatus::Optimal){out.status=CuttingStatus::LPSolveFailed;return out;}out.fractionalVariables=0;for(const auto& v:original.variables)if((v.type==VariableType::Integer||v.type==VariableType::Binary)&&v.originalId<lp.solution.primal.size()&&std::abs(lp.solution.primal[v.originalId]-std::round(lp.solution.primal[v.originalId]))>tol_)++out.fractionalVariables;if(out.fractionalVariables==0){out.status=CuttingStatus::OptimalInteger;out.solution=lp.solution.primal;out.objective=evaluateObjective(original,out.solution);out.verified=verify(original,out.solution,tol_);return out;}if(out.cutsAccepted>=maxCuts_){out.status=CuttingStatus::CutLimitReached;return out;}Constraint cut;cut.originalId=work.constraints.size();cut.activeId=cut.originalId;std::size_t src=0;++out.cutsGenerated;if(!gen.generate(lp,work,cut,src)){++out.cutsRejected;out.status=CuttingStatus::NumericalFailure;return out;}bool duplicate=false;for(const auto& c:work.constraints)if(c.relation==cut.relation&&std::abs(c.rhs-cut.rhs)<=tol_&&c.coefficients.size()==cut.coefficients.size()){bool same=true;for(auto p:cut.coefficients)if(!c.coefficients.count(p.first)||std::abs(c.coefficients.at(p.first)-p.second)>tol_)same=false;if(same)duplicate=true;}if(duplicate){++out.cutsRejected;out.status=CuttingStatus::NumericalFailure;return out;}work.constraints.push_back(std::move(cut));++out.cutsAccepted;}out.status=CuttingStatus::IterationLimitReached;return out;}
private: double tol_;std::size_t maxCuts_,maxIterations_;static bool verify(const Model&m,const std::vector<double>&x,double t){for(const auto&v:m.variables){if(v.originalId>=x.size()||x[v.originalId]<v.lower-t||(std::isfinite(v.upper)&&x[v.originalId]>v.upper+t))return false;if((v.type==VariableType::Integer||v.type==VariableType::Binary)&&std::abs(x[v.originalId]-std::round(x[v.originalId]))>t)return false;}for(const auto&c:m.constraints){double a=0;for(auto q:c.coefficients)a+=q.second*x[q.first];if(c.relation==Relation::Equal&&std::abs(a-c.rhs)>t)return false;if(c.relation==Relation::LessEqual&&a>c.rhs+t)return false;if(c.relation==Relation::GreaterEqual&&a<c.rhs-t)return false;}return true;}};
}

