#include "presolve/Presolver.hpp"
#include "model/Input.hpp"
#include "model/Classification.hpp"
#include "lp/LPSolver.hpp"
#include "lp/DualSimplex.hpp"
#include "lp/MehrotraIPM.hpp"
#include "presolve/Postsolve.hpp"
#include "qp/Convexity.hpp"
#include "qp/QPIPM.hpp"
#include "qp/GeneralQP.hpp"
#include "milp/LPRelaxation.hpp"
#include "milp/BranchAndBound.hpp"
#include "milp/CuttingPlane.hpp"
#include "milp/FeasibilityPump.hpp"
#include <iostream>
using namespace sovereign;
int main(int argc,char** argv){
 if(argc<3||std::string(argv[1])!="--input"){std::cerr<<"usage: --input <file> [--method revised-simplex|dual-simplex|ipm|qp]\n";return 2;}
 try{Model model=parseInput(argv[2]);auto cls=classify(model);auto red=Presolver{}.run(model);LPMethod method=LPMethod::RevisedSimplex;
  for(int i=3;i+1<argc;++i)if(std::string(argv[i])=="--method"){std::string x=argv[i+1];if(x=="dual-simplex")method=LPMethod::DualSimplex;else if(x=="ipm")method=LPMethod::IPM;}
  std::cout<<"MODEL "<<model.name<<"\nVariables: "<<model.variables.size()<<"\nConstraints: "<<model.constraints.size()<<"\nPRESOLVE\nFinal variables: "<<red.model.variables.size()<<"\nFinal constraints: "<<red.model.constraints.size()<<"\n";
  bool qp=false,relax=false;LPMethod lpMethod=LPMethod::RevisedSimplex;for(int i=3;i+1<argc;++i){if(std::string(argv[i])=="--method"&&std::string(argv[i+1])=="qp")qp=true;if(std::string(argv[i])=="--method"&&std::string(argv[i+1])=="lp-relaxation")relax=true;if(std::string(argv[i])=="--lp-method"){std::string z=argv[i+1];if(z=="dual-simplex")lpMethod=LPMethod::DualSimplex;else if(z=="ipm")lpMethod=LPMethod::IPM;}}
  bool milp=false,cutting=false,fp=false;for(int i=3;i+1<argc;++i){if(std::string(argv[i])=="--method"&&std::string(argv[i+1])=="milp")milp=true;if(std::string(argv[i])=="--method"&&std::string(argv[i+1])=="cutting-plane")cutting=true;if(std::string(argv[i])=="--method"&&std::string(argv[i+1])=="feasibility-pump")fp=true;}
  if(fp){std::size_t lim=100;double tol=1e-7;for(int i=3;i+1<argc;++i){if(std::string(argv[i])=="--max-fp-iterations")lim=std::stoul(argv[i+1]);if(std::string(argv[i])=="--fp-tolerance")tol=std::stod(argv[i+1]);}auto s=FeasibilityPump{tol,lim}.solve(model);std::cout<<"Problem Type: MILP\nMethod: Feasibility Pump\nStatus: "<<(s.status==FpStatus::Feasible?"FEASIBLE":s.status==FpStatus::NoFeasibleSolution?"NO_FEASIBLE_SOLUTION":s.status==FpStatus::LPFailure?"LP_FAILURE":"NUMERICAL_FAILURE")<<"\nIterations: "<<s.iterations<<"\nRounding Attempts: "<<s.roundingAttempts<<"\nProjections: "<<s.projections<<"\nPerturbations: "<<s.perturbations<<"\nObjective: "<<s.objective<<"\nInteger Feasible: "<<(s.status==FpStatus::Feasible?"YES":"NO")<<"\nVerification: "<<(s.verified?"PASS":"N/A")<<"\n";return 0;}
  if(cutting){std::size_t cuts=100,its=100;for(int i=3;i+1<argc;++i){if(std::string(argv[i])=="--max-cuts")cuts=std::stoul(argv[i+1]);if(std::string(argv[i])=="--max-iterations")its=std::stoul(argv[i+1]);}auto s=CuttingPlaneSolver{1e-8,cuts,its}.solve(model);const char*status=s.status==CuttingStatus::OptimalInteger?"OPTIMAL_INTEGER":s.status==CuttingStatus::Infeasible?"INFEASIBLE":s.status==CuttingStatus::CutLimitReached?"CUT_LIMIT_REACHED":s.status==CuttingStatus::IterationLimitReached?"ITERATION_LIMIT_REACHED":s.status==CuttingStatus::LPSolveFailed?"LP_SOLVE_FAILED":"NUMERICAL_FAILURE";std::cout<<"Problem Type: MILP\nMethod: Cutting Plane\nCut Type: Gomory\nStatus: "<<status<<"\nIterations: "<<s.iterations<<"\nCuts Generated: "<<s.cutsGenerated<<"\nCuts Accepted: "<<s.cutsAccepted<<"\nCuts Rejected: "<<s.cutsRejected<<"\nLP Solves: "<<s.lpSolves<<"\nObjective: "<<s.objective<<"\nFractional Variables: "<<s.fractionalVariables<<"\nVerification: "<<(s.verified?"PASS":"FAIL")<<"\n";return 0;}
  if(milp){auto s=BranchAndBound{}.solve(model,lpMethod);std::cout<<"Problem Type: MILP\nMethod: Branch-and-Bound\nStatus: "<<(s.status==MILPStatus::Optimal?"OPTIMAL":s.status==MILPStatus::Infeasible?"INFEASIBLE":s.status==MILPStatus::Unbounded?"UNBOUNDED":"ITERATION_LIMIT")<<"\nObjective: "<<s.objective<<"\nPrimal Bound: "<<s.primalBound<<"\nDual Bound: "<<s.dualBound<<"\nAbsolute Gap: "<<s.absoluteGap<<"\nRelative Gap: "<<s.relativeGap<<"\nNodes Created: "<<s.nodesCreated<<"\nNodes Processed: "<<s.nodesProcessed<<"\nNodes Pruned: "<<s.nodesPruned<<"\nLP Solves: "<<s.lpSolves<<"\nVerification: "<<(s.verified?"PASS":"FAIL")<<"\n";return 0;}
  if(relax){auto s=solveLPRelaxation(model,lpMethod);std::cout<<"Problem Type: MILP\nMethod: LP Relaxation\nRelaxed Problem Type: LP\nLP Method: "<<s.method<<"\nStatus: "<<(s.status==LPStatus::Optimal?"OPTIMAL":s.status==LPStatus::Infeasible?"INFEASIBLE":s.status==LPStatus::Unbounded?"UNBOUNDED":"FAILED")<<"\nObjective: "<<s.objectiveValue<<"\nBound Type: "<<s.boundType<<"\nLP Bound: "<<s.bound<<"\nFractional Integer Variables: "<<s.fractionalIntegerVariables<<"\nFractional Solution: "<<(s.fractionalSolution?"true":"false")<<"\nIntegral Within Tolerance: "<<(s.integralWithinTolerance?"true":"false")<<"\nIterations: "<<s.iterations<<"\nVerification: "<<(s.status==LPStatus::Optimal&&s.primalResidual<=1e-7?"PASS":"FAIL")<<"\n";return 0;}
  if(qp){auto q=checkQPConvexity(model);std::cout<<"Problem Type: QP\nConvexity: "<<(q.isConvex?"CONVEX":"NON-CONVEX")<<"\nHessian: "<<convexityName(q.classification)<<"\n";auto s=GeneralQPInteriorPoint{}.solve(model);std::cout<<"Method: QP Newton Barrier\nStatus: "<<(s.status==QPStatus::Optimal?"OPTIMAL":s.status==QPStatus::UnsupportedNonconvex?"UNSUPPORTED_NONCONVEX":s.status==QPStatus::IterationLimit?"ITERATION_LIMIT":s.status==QPStatus::Unsupported?"UNSUPPORTED":"NUMERICAL_FAILURE")<<"\nIterations: "<<s.iterations<<"\nObjective: "<<s.objectiveValue<<"\nPrimal residual: "<<s.primalResidual<<"\nDual residual: "<<s.dualResidual<<"\nComplementarity: "<<s.complementarity<<"\nVerification: "<<(s.status==QPStatus::Optimal&&s.primalResidual<=1e-7?"PASS":"FAIL")<<"\nMessage: "<<s.message<<"\n";return 0;}
  if(cls.type!=ProblemType::LP){std::cout<<"SOLVER Status: UNSUPPORTED\n";return 0;}if(red.status==PresolveStatus::Infeasible){std::cout<<"SOLVER Status: INFEASIBLE\n";return 0;}if(red.status==PresolveStatus::Unbounded){std::cout<<"SOLVER Status: UNBOUNDED\n";return 0;}
  LPResult solved=method==LPMethod::DualSimplex?DualSimplex{}.solve(red.model):method==LPMethod::IPM?MehrotraIPM{}.solve(red.model):LPSolver{}.solve(red.model,method);auto sol=postsolve(model,red,solved.solution);double vr=0;for(const auto& c:model.constraints){double a=0;for(auto p:c.coefficients)a+=p.second*sol.primal[p.first];vr=std::max(vr,c.relation==Relation::Equal?std::abs(a-c.rhs):c.relation==Relation::LessEqual?std::max(0.,a-c.rhs):std::max(0.,c.rhs-a));}bool verified=solved.status==LPStatus::Optimal&&sol.primal.size()==model.variables.size()&&vr<=1e-8;std::cout<<"METHOD: "<<(method==LPMethod::DualSimplex?"DUAL SIMPLEX":method==LPMethod::IPM?"MEHROTRA IPM":"REVISED SIMPLEX")<<"\nStatus: "<<(solved.status==LPStatus::Optimal?"OPTIMAL":solved.status==LPStatus::Infeasible?"INFEASIBLE":solved.status==LPStatus::Unbounded?"UNBOUNDED":"FAILED")<<"\nIterations: "<<solved.iterations<<"\nObjective: "<<solved.objectiveValue<<"\nFeasibility: "<<vr<<"\nVerification: "<<(verified?"PASS":"FAIL")<<"\nPrimal:";for(double v:sol.primal)std::cout<<" "<<v;std::cout<<"\n";if(!solved.message.empty())std::cout<<"Message: "<<solved.message<<"\n";
  if(vr>1e-8){std::cout<<"PRIMAL";for(double x:sol.primal)std::cout<<" "<<x;std::cout<<"\nREDUCED";for(double x:solved.solution.primal)std::cout<<" "<<x;std::cout<<"\n";for(const auto& c:model.constraints){double a=0;for(auto p:c.coefficients)a+=p.second*sol.primal[p.first];double e=c.relation==Relation::Equal?std::abs(a-c.rhs):c.relation==Relation::LessEqual?std::max(0.,a-c.rhs):std::max(0.,c.rhs-a);if(e>1e-8)std::cout<<"VIOLATION "<<c.name<<" "<<a<<" "<<c.rhs<<"\n";}}
 }catch(const std::exception& e){std::cerr<<"error: "<<e.what()<<"\n";return 1;}return 0;}
